### ISSUE TITLE
Setup SourceCred for contribution

### ISSUE THREAD

**Issue by bt3gl** [midsummerDAO/call-for-help#10]
## Task

- [here](https://sourcecred.io/docs/beta/setup-guide/)
- [our fork](https://github.com/midsummerDAO/midsummer_cred)
- needs to set gh actions
- msg twitter, discord and add docs

## Reward

dm @bt3gl

**Comment by hisergiorojas** [comment]
I would like to work on this issue.

**Comment by hisergiorojas** [comment]
Can you create a gh-pages branch in https://github.com/midsummerDAO/midsummer_cred repo.
